### PR TITLE
TEIIDTOOLS-737 deprecating the validation methods

### PR DESCRIPTION
**Pull request by shawkins**
This makes the validation change mentioned on TEIIDTOOLS-737.  Once the ui is changed, we can then remove the KomodoVdbService.

### CODE REVIEW

**Comment by rareddy** [comment]
LGTM - Should we log another issue to remove the deprecation and fix the UI side?

**Comment by mdrillin** [comment]
> LGTM - Should we log another issue to remove the deprecation and fix the UI side?

No need to log another issue for UI work - I can work the UI side under TTOOLS-737.

**Comment by rareddy** [comment]
:+1: Please also remove deprecated calls in that commit.

**Comment by shawkins** [comment]
I should add that there is one small difference in that this does not validate virtualization names against connection names as the validate method did.  Would you be ok with it returning a 303 "see other" code if the name matches a source name?

**Comment by mdrillin** [comment]
I'm ok with the 303 code.  I'm not clear atm how to validate view names.  What is service call for that?

**Comment by shawkins** [comment]
> I'm ok with the 303 code. I'm not clear atm how to validate view names. What is service call for that?

This adds GET dataservices/**name**/views/**name** - if you call that and get anything other than a 404, you'll know that the name is invalid (forbidden), an existing data virtualzation, or a connenction name (see other).

**Comment by mdrillin** [comment]
I finished the UI side changes to remove the nameValidation service calls and adapted to the GET service calls.  https://github.com/syndesisio/syndesis/pull/6875
Will merge once the UI PR is approved and ready to merge.

**Pull request merged**
