### PR TITLE
ENTESB-11790: in preparation to keep all images and versions in sync …

### PR DESCRIPTION
**Pull request by rareddy**
…with Syndesis the version is being updated 1.8.1 on this branch. Also build docker images this

### CODE REVIEW

**Comment by shawkins** [comment]
What of this should go to master?

**Comment by rareddy** [comment]
I do not have a right recipe yet, it is not working as I was expecting, it is tedious to work with travis to make changes. I want scrape the TAG and push that to docker hub as versioned one

**Comment by rareddy** [comment]
@shawkins BTW here is the latest, maybe you can help fix as I have no idea why it wrong still https://github.com/teiid/teiid-syndesis/blob/7.5-1.8.x/.travis.yml#L29-L38

Basically I want to scrape the tag and push that tagged image to docker.io

**Comment by shawkins** [comment]
Use:

    TAG=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) ;
    TAG=`echo $TAG | cut -d'-' -f 1` ;
    TAGD="$TAG-$(date +"%Y%m%d")";

**Comment by rareddy** [comment]
Thanks a bunch. I will update and issue issue PRs

**Pull request merged**
